In [1]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

import warnings
warnings.simplefilter("ignore")

In [2]:
# Loading the dataset
data = pd.read_csv("bully_1.csv")

In [3]:
data.head(10)

comments  tagging
0                             Get fucking real dude.        1
1   She is as dirty as they come  and that crook ...        1
2   why did you fuck it up. I could do it all day...        1
3   Dude they dont finish enclosing the fucking s...        1
4   WTF are you talking about Men? No men thats n...        1
5  Ill save you the trouble sister. Here comes a ...        1
6   Im dead serious.Real athletes never cheat don...        1
7  ...go absolutely insane.hate to be the bearer ...        1
8  Lmao  im watching the same thing ahaha. The ga...        1
9  LOL  no he said  What do you call a jail cell ...        1

In [4]:
# value count for each language
data["tagging"].value_counts()

tagging
0    12179
1     7822
Name: count, dtype: int64

In [5]:
# separating the independent and dependant features
X = data["comments"]
y = data["tagging"]

In [6]:
# converting categorical variables to numerical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# Text Preprocessing

In [7]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [8]:
data_list = []
for text in X:
    text = re.sub(r'[!@#$(),.\n"%^*?\:;~`0-9]', ' ', text)
    text = re.sub(r'[[]]', ' ', text)
    text = re.sub(r'\[.*?\]', ' ', text)
    text = text.lower()
    data_list.append(text)

data = pd.DataFrame({'comments': data_list})

In [9]:
data['Tokenized_Text'] = data['comments'].apply(word_tokenize)
data

comments  \
0                                 get fucking real dude    
1       she is as dirty as they come  and that crook ...   
2       why did you fuck it up  i could do it all day...   
3       dude they dont finish enclosing the fucking s...   
4       wtf are you talking about men  no men thats n...   
...                                                  ...   
19996    i dont  but what is complaining about it goi...   
19997   bahah  yeah i& m totally just gonna&  get pis...   
19998       hahahahaha >   im evil mwahahahahahahahahaha   
19999            what& s something unique about ohio       
20000              who is the biggest gossiper you know    

                                          Tokenized_Text  
0                             [get, fucking, real, dude]  
1      [she, is, as, dirty, as, they, come, and, that...  
2      [why, did, you, fuck, it, up, i, could, do, it...  
3      [dude, they, dont, finish, enclosing, the, fuc...  
4      [wtf, are, you, talking, about, men, no, men, ...  
...                                                  ...  
19996  [i, dont, but, what, is, complaining, about, i...  
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...  
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]  
19999       [what, &, s, something, unique, about, ohio]  
20000       [who, is, the, biggest, gossiper, you, know]  

[20001 rows x 2 columns]

In [10]:
from nltk.stem import PorterStemmer
porter_stemmer = PorterStemmer()
data['Stemmed_Text'] = data['Tokenized_Text'].apply(lambda tokens: [porter_stemmer.stem(token) for token in tokens])
data

comments  \
0                                 get fucking real dude    
1       she is as dirty as they come  and that crook ...   
2       why did you fuck it up  i could do it all day...   
3       dude they dont finish enclosing the fucking s...   
4       wtf are you talking about men  no men thats n...   
...                                                  ...   
19996    i dont  but what is complaining about it goi...   
19997   bahah  yeah i& m totally just gonna&  get pis...   
19998       hahahahaha >   im evil mwahahahahahahahahaha   
19999            what& s something unique about ohio       
20000              who is the biggest gossiper you know    

                                          Tokenized_Text  \
0                             [get, fucking, real, dude]   
1      [she, is, as, dirty, as, they, come, and, that...   
2      [why, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclosing, the, fuc...   
4      [wtf, are, you, talking, about, men, no, men, ...   
...                                                  ...   
19996  [i, dont, but, what, is, complaining, about, i...   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999       [what, &, s, something, unique, about, ohio]   
20000       [who, is, the, biggest, gossiper, you, know]   

                                            Stemmed_Text  
0                                [get, fuck, real, dude]  
1      [she, is, as, dirti, as, they, come, and, that...  
2      [whi, did, you, fuck, it, up, i, could, do, it...  
3      [dude, they, dont, finish, enclos, the, fuck, ...  
4      [wtf, are, you, talk, about, men, no, men, tha...  
...                                                  ...  
19996  [i, dont, but, what, is, complain, about, it, ...  
19997  [bahah, yeah, i, &, m, total, just, gon, na, &...  
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]  
19999           [what, &, s, someth, uniqu, about, ohio]  
20000         [who, is, the, biggest, gossip, you, know]  

[20001 rows x 3 columns]

In [11]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
data['Lemmatized_Text'] = data['Tokenized_Text'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
data

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


comments  \
0                                 get fucking real dude    
1       she is as dirty as they come  and that crook ...   
2       why did you fuck it up  i could do it all day...   
3       dude they dont finish enclosing the fucking s...   
4       wtf are you talking about men  no men thats n...   
...                                                  ...   
19996    i dont  but what is complaining about it goi...   
19997   bahah  yeah i& m totally just gonna&  get pis...   
19998       hahahahaha >   im evil mwahahahahahahahahaha   
19999            what& s something unique about ohio       
20000              who is the biggest gossiper you know    

                                          Tokenized_Text  \
0                             [get, fucking, real, dude]   
1      [she, is, as, dirty, as, they, come, and, that...   
2      [why, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclosing, the, fuc...   
4      [wtf, are, you, talking, about, men, no, men, ...   
...                                                  ...   
19996  [i, dont, but, what, is, complaining, about, i...   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999       [what, &, s, something, unique, about, ohio]   
20000       [who, is, the, biggest, gossiper, you, know]   

                                            Stemmed_Text  \
0                                [get, fuck, real, dude]   
1      [she, is, as, dirti, as, they, come, and, that...   
2      [whi, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclos, the, fuck, ...   
4      [wtf, are, you, talk, about, men, no, men, tha...   
...                                                  ...   
19996  [i, dont, but, what, is, complain, about, it, ...   
19997  [bahah, yeah, i, &, m, total, just, gon, na, &...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999           [what, &, s, someth, uniqu, about, ohio]   
20000         [who, is, the, biggest, gossip, you, know]   

                                         Lemmatized_Text  
0                             [get, fucking, real, dude]  
1      [she, is, a, dirty, a, they, come, and, that, ...  
2      [why, did, you, fuck, it, up, i, could, do, it...  
3      [dude, they, dont, finish, enclosing, the, fuc...  
4      [wtf, are, you, talking, about, men, no, men, ...  
...                                                  ...  
19996  [i, dont, but, what, is, complaining, about, i...  
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...  
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]  
19999       [what, &, s, something, unique, about, ohio]  
20000       [who, is, the, biggest, gossiper, you, know]  

[20001 rows x 4 columns]

In [12]:
data['Char_Count'] = [len(text) for text in data['comments']]
data['Word_Count'] = [len(tokens) for tokens in data['Lemmatized_Text']]
data

comments  \
0                                 get fucking real dude    
1       she is as dirty as they come  and that crook ...   
2       why did you fuck it up  i could do it all day...   
3       dude they dont finish enclosing the fucking s...   
4       wtf are you talking about men  no men thats n...   
...                                                  ...   
19996    i dont  but what is complaining about it goi...   
19997   bahah  yeah i& m totally just gonna&  get pis...   
19998       hahahahaha >   im evil mwahahahahahahahahaha   
19999            what& s something unique about ohio       
20000              who is the biggest gossiper you know    

                                          Tokenized_Text  \
0                             [get, fucking, real, dude]   
1      [she, is, as, dirty, as, they, come, and, that...   
2      [why, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclosing, the, fuc...   
4      [wtf, are, you, talking, about, men, no, men, ...   
...                                                  ...   
19996  [i, dont, but, what, is, complaining, about, i...   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999       [what, &, s, something, unique, about, ohio]   
20000       [who, is, the, biggest, gossiper, you, know]   

                                            Stemmed_Text  \
0                                [get, fuck, real, dude]   
1      [she, is, as, dirti, as, they, come, and, that...   
2      [whi, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclos, the, fuck, ...   
4      [wtf, are, you, talk, about, men, no, men, tha...   
...                                                  ...   
19996  [i, dont, but, what, is, complain, about, it, ...   
19997  [bahah, yeah, i, &, m, total, just, gon, na, &...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999           [what, &, s, someth, uniqu, about, ohio]   
20000         [who, is, the, biggest, gossip, you, know]   

                                         Lemmatized_Text  Char_Count  \
0                             [get, fucking, real, dude]          23   
1      [she, is, a, dirty, a, they, come, and, that, ...         130   
2      [why, did, you, fuck, it, up, i, could, do, it...         130   
3      [dude, they, dont, finish, enclosing, the, fuc...         126   
4      [wtf, are, you, talking, about, men, no, men, ...          75   
...                                                  ...         ...   
19996  [i, dont, but, what, is, complaining, about, i...          55   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...         128   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]          46   
19999       [what, &, s, something, unique, about, ohio]          40   
20000       [who, is, the, biggest, gossiper, you, know]          38   

       Word_Count  
0               4  
1              25  
2              31  
3              21  
4              16  
...           ...  
19996          11  
19997          30  
19998           5  
19999           7  
20000           7  

[20001 rows x 6 columns]

In [13]:
data_list1 = []
for text_list in data['Lemmatized_Text']:
    text = ' '.join(text_list)
    text = text.lower()
    data_list1.append(text)

In [22]:
data_list1

['get fucking real dude',
 "she is a dirty a they come and that crook rengel the dems are so fucking corrupt it 's a joke make republican look like",
 "why did you fuck it up i could do it all day too let 's do it when you have an hour ping me later to sched writing a book here",
 'dude they dont finish enclosing the fucking shower i hate half assed job whats the reasononing behind it make no sense',
 "wtf are you talking about men no men thats not a menage that 's just gay",
 'ill save you the trouble sister here come a big ol fuck france block coming your way here on the twitter',
 "im dead serious real athlete never cheat do n't even have the appearance of at his level fuck him dude seriously i think he did",
 'go absolutely insane hate to be the bearer of bad news lol dont shoot the messenger cause we all know you bought that pistol',
 'lmao im watching the same thing ahaha the gay guy is hilarious dede having a good day and i dont want anyone to mess it up',
 'lol no he said what 

In [14]:
df=data.copy()

In [15]:
from nltk.util import ngrams
text_data = df['Lemmatized_Text']
df['Bigrams'] = df['Lemmatized_Text'].apply(lambda x: list(ngrams(x, 2)))
df['Trigrams'] = df['Lemmatized_Text'].apply(lambda x: list(ngrams(x, 3)))
# df['Bigrams'] = df['Lemmatized_Text'].apply(lambda x: list(ngrams(x, 2)))
# df['Bigrams'] = df['Lemmatized_Text'].apply(lambda x: list(ngrams(x, 2)))
df

comments  \
0                                 get fucking real dude    
1       she is as dirty as they come  and that crook ...   
2       why did you fuck it up  i could do it all day...   
3       dude they dont finish enclosing the fucking s...   
4       wtf are you talking about men  no men thats n...   
...                                                  ...   
19996    i dont  but what is complaining about it goi...   
19997   bahah  yeah i& m totally just gonna&  get pis...   
19998       hahahahaha >   im evil mwahahahahahahahahaha   
19999            what& s something unique about ohio       
20000              who is the biggest gossiper you know    

                                          Tokenized_Text  \
0                             [get, fucking, real, dude]   
1      [she, is, as, dirty, as, they, come, and, that...   
2      [why, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclosing, the, fuc...   
4      [wtf, are, you, talking, about, men, no, men, ...   
...                                                  ...   
19996  [i, dont, but, what, is, complaining, about, i...   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999       [what, &, s, something, unique, about, ohio]   
20000       [who, is, the, biggest, gossiper, you, know]   

                                            Stemmed_Text  \
0                                [get, fuck, real, dude]   
1      [she, is, as, dirti, as, they, come, and, that...   
2      [whi, did, you, fuck, it, up, i, could, do, it...   
3      [dude, they, dont, finish, enclos, the, fuck, ...   
4      [wtf, are, you, talk, about, men, no, men, tha...   
...                                                  ...   
19996  [i, dont, but, what, is, complain, about, it, ...   
19997  [bahah, yeah, i, &, m, total, just, gon, na, &...   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]   
19999           [what, &, s, someth, uniqu, about, ohio]   
20000         [who, is, the, biggest, gossip, you, know]   

                                         Lemmatized_Text  Char_Count  \
0                             [get, fucking, real, dude]          23   
1      [she, is, a, dirty, a, they, come, and, that, ...         130   
2      [why, did, you, fuck, it, up, i, could, do, it...         130   
3      [dude, they, dont, finish, enclosing, the, fuc...         126   
4      [wtf, are, you, talking, about, men, no, men, ...          75   
...                                                  ...         ...   
19996  [i, dont, but, what, is, complaining, about, i...          55   
19997  [bahah, yeah, i, &, m, totally, just, gon, na,...         128   
19998   [hahahahaha, >, im, evil, mwahahahahahahahahaha]          46   
19999       [what, &, s, something, unique, about, ohio]          40   
20000       [who, is, the, biggest, gossiper, you, know]          38   

       Word_Count                                            Bigrams  \
0               4    [(get, fucking), (fucking, real), (real, dude)]   
1              25  [(she, is), (is, a), (a, dirty), (dirty, a), (...   
2              31  [(why, did), (did, you), (you, fuck), (fuck, i...   
3              21  [(dude, they), (they, dont), (dont, finish), (...   
4              16  [(wtf, are), (are, you), (you, talking), (talk...   
...           ...                                                ...   
19996          11  [(i, dont), (dont, but), (but, what), (what, i...   
19997          30  [(bahah, yeah), (yeah, i), (i, &), (&, m), (m,...   
19998           5  [(hahahahaha, >), (>, im), (im, evil), (evil, ...   
19999           7  [(what, &), (&, s), (s, something), (something...   
20000           7  [(who, is), (is, the), (the, biggest), (bigges...   

                                                Trigrams  
0          [(get, fucking, real), (fucking, real, dude)]  
1      [(she, is, a), (is, a, dirty),

# Bag of Words

In [16]:
# creating bag of words using countvectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(data_list1).toarray()

In [17]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
X.shape

(20001, 14992)

# Train Test Split

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [20]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

# Initialize the QDA model
qda = QuadraticDiscriminantAnalysis()





In [21]:
print(x_train)
print(y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 0 1 ... 1 1 0]


In [ ]:
# Fit the model to the training data
qda.fit(x_train, y_train)

In [21]:
y_pred = qda.predict(x_test)


In [22]:
qda.score(x_test, y_test)

0.9010247438140465

In [23]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Initialize the LDA model
lda = LinearDiscriminantAnalysis()

# Fit the model to the training data directly, without converting to array
lda.fit(x_train, y_train)


LinearDiscriminantAnalysis()

In [24]:
y_pred = lda.predict(x_test)

In [25]:
lda.score(x_test, y_test)

0.7990502374406399

# Saving the model

In [26]:
import pickle

# save the iris classification model as a pickle file
model_pkl_file = "CyberBullyingQDA.pkl"  

with open(model_pkl_file, 'wb') as file:  
    pickle.dump(qda, file)
